# api:
#   interval: 60s
#   uri: "http://requestb.in/13gerls1"
#   key: "48593282-b38d-4bf5-af58-f7327271e73d"
#   pid: "something-static"
# sessions:
#   uri: file:///tmp/transporter.state
#   interval: 2s
#   type: "filestore"
nodes:
  localmongo:
    type: mongodb
    uri: mongodb://127.0.0.1/
    Timeout: 1000s
    debug: true
    namespace: articles.articles_pubmed
    tail: true
  es:
    type: elasticsearch
    uri: http://127.0.0.1:9200/
    namespace: articles_pubmed.article
