# api:
#   interval: 60s
#   uri: "http://requestb.in/13gerls1"
#   key: "48593282-b38d-4bf5-af58-f7327271e73d"
#   pid: "something-static"
# sessions:
#   uri: file:///tmp/transporter.state
#   interval: 2s
#   type: "filestore"
nodes:
  localmongo:
    type: mongodb
    uri: mongodb://127.0.0.1/
    Timeout: 1000s
    debug: true
    namespace: articles.articles
    tail: true
  es:
    type: elasticsearch
    uri: http://127.0.0.1:9200/
    namespace: articles_v7.article
  timeseries:
    type: influx
    uri: influxdb://root:root@localhost:8086/compose
  debug:
    type: file
    uri: stdout://
  tofile:
    type: file
    uri: file:///tmp/foo2
  errorfile:
    type: file
    uri: file:///var/gonnaerror
  stdout:
    type: file
    uri: stdout://
  rethink1:
    type: rethinkdb
    uri: rethink://localhost:28015/
  loosefile:
    type: file
  logtransformer:
    filename: test/transformers/passthrough_and_log.js
    type: transformer
